import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar} from 'recharts';
import {Sprout,TrendingUp,Users,Truck,Warehouse,ShieldCheck,PlusCircle,Send,AlertTriangle,IndianRupee,MapPin} from 'lucide-react';
import './styles.css';
const API='https://agrisetu-tejw.onrender.com/api';
function App(){
 const [tab,setTab]=useState('Dashboard'); const [markets,setMarkets]=useState([]); const [buyers,setBuyers]=useState([]); const [trend,setTrend]=useState({labels:[],prices:[],forecast:[]}); const [rec,setRec]=useState(null); const [lots,setLots]=useState([]); const [msg,setMsg]=useState('');
 const [form,setForm]=useState({crop:'Onion',quantity_kg:500,location:'Dhule',quality:'Grade A',harvest_date:'2026-09-10',farmer:'Demo Farmer'});
 const load=async()=>{let [m,b,t,r,l]=await Promise.all([fetch(API+'/markets').then(x=>x.json()),fetch(API+'/buyers').then(x=>x.json()),fetch(API+'/price-trend').then(x=>x.json()),fetch(API+'/recommendation').then(x=>x.json()),fetch(API+'/lots').then(x=>x.json())]);setMarkets(m.markets);setBuyers(b.buyers);setTrend(t);setRec(r);setLots(l.lots)};
 useEffect(()=>{load()},[]);
 const createLot=async()=>{let r=await fetch(API+'/lots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){setMsg('Produce lot created successfully.');load();setTab('Lots')}};
 const chart=trend.labels.map((x,i)=>({day:x,price:trend.prices[i],forecast:i===11?trend.forecast[0]:null}));
 return <div className="app"><aside><div className="brand"><Sprout size={34}/><div><b>AgriSetu</b><small>Better Decisions • Higher Returns</small></div></div><nav>{['Dashboard','Market Intelligence','Create Lot','Buyers & Offers','Logistics & Storage','Payments','Grievances'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="sideTip">Know the right price.<br/>Find the right buyer.<br/>Sell at the right time.</div></aside><main><header><div><h1>{tab}</h1><p>Smart farm-to-buyer market & transaction platform</p></div><div className="verified"><ShieldCheck/> Verified data workflow</div></header>{msg&&<div className="toast">{msg}</div>}
 {tab==='Dashboard'&&<Dashboard rec={rec} markets={markets} trend={chart} buyers={buyers} lots={lots} setTab={setTab}/>}
 {tab==='Market Intelligence'&&<Markets markets={markets} trend={chart} rec={rec}/>} 
 {tab==='Create Lot'&&<CreateLot form={form} setForm={setForm} createLot={createLot}/>} 
 {tab==='Buyers & Offers'&&<Buyers buyers={buyers} rec={rec}/>} 
 {tab==='Logistics & Storage'&&<Logistics/>}
 {tab==='Payments'&&<Payments/>}
 {tab==='Grievances'&&<Grievances/>}
 {tab==='Lots'&&<Dashboard rec={rec} markets={markets} trend={chart} buyers={buyers} lots={lots} setTab={setTab}/>} 
 </main></div>
}
function Card({icon,title,value,sub}){return <div className="card stat"><div className="icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Dashboard({rec,markets,trend,buyers,lots,setTab}){return <><div className="grid4"><Card icon={<IndianRupee/>} title="Best net realisation" value={rec?`₹${rec.market.net_realisation}/kg`:'—'} sub={rec?.market.name}/><Card icon={<TrendingUp/>} title="Market trend" value={rec?`+${rec.market.trend}%`: '—'} sub="recent trend"/><Card icon={<Users/>} title="Verified buyers" value={buyers.filter(x=>x.verified).length} sub="trust-layer screened"/><Card icon={<Sprout/>} title="Active lots" value={lots.length} sub="ready for offers"/></div><div className="two"><section className="panel"><div className="panelHead"><h2>Price trend & forecast</h2><span>₹/kg</span></div><ResponsiveContainer width="100%" height={280}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line type="monotone" dataKey="price" strokeWidth={3}/><Line type="monotone" dataKey="forecast" strokeWidth={3} strokeDasharray="6 4"/></LineChart></ResponsiveContainer></section><section className="panel rec"><div className="recommend"><span>AI SELLING RECOMMENDATION</span><h2>{rec?.recommendation||'Calculating...'}</h2><p>{rec?.reason}</p><div className="recbox"><b>{rec?.market.name}</b><span>Net realisation <strong>₹{rec?.market.net_realisation}/kg</strong></span></div><div className="recbox"><b>{rec?.buyer.name}</b><span>{rec?.buyer.type} • {rec?.buyer.rating}★ • {rec?.buyer.payment_days} days</span></div><button onClick={()=>setTab('Create Lot')}><PlusCircle size={18}/> Create produce lot</button></div></section></div><section className="panel"><div className="panelHead"><h2>How AgriSetu creates value</h2></div><div className="steps"><Step n="1" t="Market data" s="prices • arrivals • demand"/><Step n="2" t="Smart matching" s="quality • quantity • buyer"/><Step n="3" t="Net realisation" s="transport • storage • risk"/><Step n="4" t="Transaction" s="offer • logistics • payment"/><Step n="5" t="Outcome" s="higher, safer returns"/></div></section></>}
function Step({n,t,s}){return <div className="step"><b>{n}</b><strong>{t}</strong><small>{s}</small></div>}
function Markets({markets,trend,rec}){return <><div className="two"><section className="panel"><h2>Market price comparison</h2><div className="marketList">{markets.map(m=><div className="market"><div><MapPin size={17}/><b>{m.name}</b><small>{m.location} • {m.distance} km</small></div><strong>₹{m.price}/kg</strong><em>+{m.trend}%</em></div>)}</div></section><section className="panel"><h2>Localized price trend</h2><ResponsiveContainer width="100%" height={310}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line type="monotone" dataKey="price" strokeWidth={3}/></LineChart></ResponsiveContainer></section></div><section className="panel"><h2>Where + When + To Whom</h2><div className="decision"><div><span>Recommended market</span><b>{rec?.market.name}</b><small>₹{rec?.market.net_realisation}/kg projected net</small></div><div><span>Action</span><b>{rec?.recommendation}</b><small>Based on trend + cost + risk</small></div><div><span>Matched buyer</span><b>{rec?.buyer.name}</b><small>{rec?.buyer.rating}★ • verified • {rec?.buyer.payment_days} day payment</small></div></div></section></>}
function CreateLot({form,setForm,createLot}){return <section className="panel formPanel"><h2>Create Produce Lot</h2><p>Enter the lot once. AgriSetu can use it for buyer matching, offers, logistics and transaction records.</p><div className="formgrid">{Object.keys(form).map(k=><label>{k.replace('_',' ')}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={createLot}><Send size={18}/> Publish lot for matching</button></section>}
function Buyers({buyers,rec}){return <section className="panel"><h2>Verified Buyer Network</h2><div className="buyerGrid">{buyers.map(b=><div className="buyer"><div className="buyerTop"><Users/><span>{b.verified?'VERIFIED':'UNVERIFIED'}</span></div><h3>{b.name}</h3><p>{b.type}</p><div className="chips"><span>{b.rating}★ rating</span><span>{b.payment_days} day payment</span><span>{b.quality}</span></div><button className="outline">Send digital offer</button></div>)}</div></section>}
function Logistics(){let items=[['AgriMove','Mini Truck','₹24/km','1000 kg','4.6★'],['FarmRoute','Pickup','₹19/km','700 kg','4.4★']];return <><section className="panel"><h2>Logistics coordination</h2><div className="buyerGrid">{items.map(x=><div className="buyer"><Truck/><h3>{x[0]}</h3><p>{x[1]} • {x[3]} capacity</p><div className="chips"><span>{x[2]}</span><span>{x[4]}</span></div><button className="outline">Request transport</button></div>)}</div></section><section className="panel"><h2>Storage options</h2><div className="marketList"><div className="market"><div><Warehouse/><b>Dhule Cold Storage</b><small>9 km • 1200 kg • ₹0.85/kg/day</small></div><strong>4.6★</strong></div><div className="market"><div><Warehouse/><b>FPO Community Warehouse</b><small>6 km • 500 kg • ₹0.45/kg/day</small></div><strong>4.4★</strong></div></div></section></>}
function Payments(){return <section className="panel empty"><IndianRupee size={48}/><h2>Payment Tracking</h2><p>Digital offer → accepted → dispatch → payment received. Every status is recorded against the lot.</p><div className="timeline"><span>Offer</span><i/> <span>Accepted</span><i/> <span>Dispatch</span><i/> <span>Paid</span></div></section>}
function Grievances(){const [text,setText]=useState('');return <section className="panel formPanel"><h2>Grievance & Dispute Support</h2><p>Record a payment, quality, delivery or buyer-related issue against a transaction.</p><label>Issue description<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe the issue..."/></label><button className="primary" onClick={()=>setText('')}>Submit grievance</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
